// Introduction to Networks — ระดับกลาง
// โมเดลอ้างอิง, Ethernet/Switching, Network Layer, การแก้ปัญหา + แล็บ VPCS จริง

export default {
  slug: 'ccna-intro',
  title: 'Introduction to Networks',
  description: 'คอร์สแรกของชุด Networking — โมเดล OSI/TCP-IP, Ethernet & switching, IPv4/IPv6 และการวินิจฉัยปัญหาเครือข่าย พร้อมแล็บลงมือทำ เนื้อหาครอบคลุมหัวข้อที่สอดคล้องกับ exam objectives ระดับ CCNA',
  level: 'intermediate',
  track: 'Networking',
  estimatedHours: 70,
  prerequisites: ['เข้าใจ IP addressing และ subnetting (คอร์ส IP Addressing & Subnetting)', 'คุ้นเคยกับการใช้ ping/trace'],
  published: true,
  modules: [
    {
      title: 'โมดูล 1 — โมเดลอ้างอิง OSI และ TCP/IP',
      description: 'แบ่งการสื่อสารเป็นชั้น ๆ เพื่อให้เข้าใจและแก้ปัญหาได้เป็นระบบ',
      order: 0,
      objectives: [
        'อธิบายชั้นทั้ง 7 ของ OSI และ 4 ชั้นของ TCP/IP',
        'จับคู่ protocol กับชั้นที่เหมาะสม',
        'อธิบายกระบวนการ encapsulation/de-encapsulation',
        'แยกความต่างของ TCP กับ UDP ที่ชั้น Transport และเข้าใจ 3-way handshake/windowing',
      ],
      lessons: [
        {
          type: 'reading',
          title: 'ทำไมต้องแบ่งเป็นชั้น (Layered Model)',
          order: 0,
          estMinutes: 12,
          sections: [
            {
              heading: 'OSI 7 ชั้น',
              body: [
                'โมเดล OSI แบ่งการสื่อสารเป็น 7 ชั้น แต่ละชั้นมีหน้าที่เฉพาะและคุยกับชั้นข้างเคียง:',
                '',
                '| ชั้น | ชื่อ | ตัวอย่าง |',
                '|-----|------|----------|',
                '| 7 | Application | HTTP, DNS |',
                '| 6 | Presentation | TLS, JPEG |',
                '| 5 | Session | การจัดการ session |',
                '| 4 | Transport | TCP, UDP |',
                '| 3 | Network | IP, ICMP |',
                '| 2 | Data Link | Ethernet, MAC |',
                '| 1 | Physical | สาย, สัญญาณ |',
                '',
                'การแบ่งชั้นช่วยให้เรา**แยกแยะปัญหา**ได้ เช่น "สาย (L1) มาแล้ว แต่ IP (L3) ผิด"',
              ].join('\n'),
            },
            {
              heading: 'TCP/IP 4 ชั้น',
              body: [
                'โมเดลที่ใช้จริงบนอินเทอร์เน็ตคือ TCP/IP ซึ่งยุบ OSI ให้เหลือ 4 ชั้น:',
                '',
                '- **Application** (รวม L5–L7 ของ OSI)',
                '- **Transport** (L4)',
                '- **Internet** (L3)',
                '- **Network Access** (L1–L2)',
                '',
                'จำง่าย ๆ: OSI ไว้เรียน/วิเคราะห์ ส่วน TCP/IP คือสิ่งที่อุปกรณ์ใช้งานจริง',
              ].join('\n'),
            },
            {
              heading: 'Encapsulation',
              body: [
                'ข้อมูลจะถูกห่อ (encapsulate) ทีละชั้นจากบนลงล่าง โดยแต่ละชั้นเติม header ของตัวเอง:',
                '',
                '```',
                'Data → Segment (L4) → Packet (L3) → Frame (L2) → Bits (L1)',
                '```',
                '',
                'ฝั่งรับจะถอด header ทีละชั้นกลับขึ้นไป (de-encapsulation)',
              ].join('\n'),
            },
          ],
        },
        {
          type: 'quiz',
          title: 'แบบทดสอบ — โมเดลอ้างอิง',
          order: 1,
          estMinutes: 5,
          passThreshold: 60,
          questions: [
            {
              prompt: 'IP address ทำงานอยู่ที่ชั้นใดของ OSI',
              choices: ['Layer 2 (Data Link)', 'Layer 3 (Network)', 'Layer 4 (Transport)', 'Layer 7 (Application)'],
              answer: [1],
              explanation: 'IP เป็น protocol ชั้น Network (L3) ส่วน MAC อยู่ L2 และ TCP/UDP อยู่ L4',
              points: 1,
            },
            {
              prompt: 'หน่วยข้อมูล (PDU) ที่ชั้น Transport เรียกว่าอะไร',
              choices: ['Frame', 'Packet', 'Segment', 'Bit'],
              answer: [2],
              explanation: 'L4 = Segment, L3 = Packet, L2 = Frame, L1 = Bits',
              points: 1,
            },
            {
              prompt: 'protocol ใดทำงานที่ชั้น Transport (เลือกได้มากกว่า 1 ข้อ)',
              choices: ['TCP', 'IP', 'UDP', 'Ethernet'],
              answer: [0, 2],
              explanation: 'TCP และ UDP เป็น protocol ชั้น Transport ส่วน IP อยู่ L3 และ Ethernet อยู่ L2',
              points: 2,
            },
          ],
        },
        {
          type: 'reading',
          title: 'เจาะลึกชั้น Transport: TCP เทียบ UDP',
          order: 2,
          estMinutes: 14,
          sections: [
            {
              heading: 'หน้าที่ของชั้น Transport',
              body: [
                'ชั้น Transport (L4) เชื่อมระหว่าง "แอป" กับ "เครือข่าย" มีสามหน้าที่หลัก:',
                '',
                '- **Segmentation** — ตัดข้อมูลก้อนใหญ่จากแอปเป็นชิ้น (segment) ให้พอดีกับที่เครือข่ายส่งได้',
                '- **Multiplexing ด้วย port** — หลายแอปบนเครื่องเดียวใช้เครือข่ายพร้อมกันได้ โดยแยกกันด้วย **port number** (เช่นเบราว์เซอร์ใช้ปลายทางพอร์ต 443 ขณะที่อีเมลใช้ 25)',
                '- **เลือกระดับความน่าเชื่อถือ** — แอปเลือกได้ว่าจะใช้ **TCP** (เชื่อถือได้) หรือ **UDP** (เร็ว/เบา)',
                '',
                'ทั้ง TCP และ UDP อยู่ชั้น Transport เหมือนกัน แต่ให้คุณสมบัติคนละแบบ',
              ].join('\n'),
            },
            {
              heading: 'TCP — เชื่อถือได้ (Connection-Oriented)',
              body: [
                'TCP สร้าง "การเชื่อมต่อ" ก่อนส่งข้อมูลจริง ด้วย **3-way handshake**:',
                '',
                '```',
                'A → B : SYN          (ขอเปิดการเชื่อมต่อ)',
                'B → A : SYN-ACK      (ตอบรับ + ขอกลับ)',
                'A → B : ACK          (ยืนยัน — พร้อมส่งข้อมูล)',
                '```',
                '',
                'จากนั้นรับประกันความน่าเชื่อถือด้วย:',
                '- **Sequence/Acknowledgement number** — ลำดับทุกไบต์ ฝั่งรับ ACK บอกว่าได้ถึงไหนแล้ว',
                '- **Retransmission** — ถ้าไม่ได้ ACK ภายในเวลา ส่งซ้ำ',
                '- **Ordered delivery** — เรียงข้อมูลให้ถูกลำดับแม้มาถึงสลับกัน',
                '- **Flow control (windowing)** — ฝั่งรับบอก "หน้าต่าง" (window size) ว่ารับเพิ่มได้อีกเท่าไรก่อนต้อง ACK ป้องกันผู้ส่งกระหน่ำจนผู้รับล้น (window ปรับขึ้น/ลงได้ตามสภาพ)',
                '',
                'เหมาะกับงานที่ "ข้อมูลห้ามหาย/ห้ามสลับ": เว็บ (HTTP/HTTPS), อีเมล, โอนไฟล์',
              ].join('\n'),
            },
            {
              heading: 'UDP — เร็วและเบา (Connectionless)',
              body: [
                'UDP ส่งเลยโดยไม่มี handshake ไม่จดลำดับ ไม่ส่งซ้ำ ไม่มี flow control — "ยิงแล้วจบ" (fire-and-forget)',
                '',
                'ข้อดีคือ overhead ต่ำและหน่วงน้อย เหมาะกับงานที่ "เร็วสำคัญกว่าครบ" และยอมให้ตกหล่นได้บ้าง:',
                '- เสียง/วิดีโอเรียลไทม์ (VoIP, video call) — แพ็กเก็ตที่มาช้าไปก็ไร้ประโยชน์อยู่ดี',
                '- DNS query (ถาม-ตอบสั้น ๆ)',
                '- เกมออนไลน์, สตรีมมิง',
                '',
                '> ถ้าแอปบน UDP ต้องการความน่าเชื่อถือบางส่วน มันต้องจัดการเองในระดับแอป (TCP จัดให้หมดแล้ว)',
              ].join('\n'),
            },
            {
              heading: 'TCP เทียบ UDP และ Well-Known Ports',
              body: [
                '| ประเด็น | TCP | UDP |',
                '|---|---|---|',
                '| การเชื่อมต่อ | มี (3-way handshake) | ไม่มี |',
                '| ความน่าเชื่อถือ | รับประกัน (ACK/ส่งซ้ำ) | ไม่รับประกัน |',
                '| ลำดับข้อมูล | เรียงให้ | ไม่เรียง |',
                '| Flow control | มี (windowing) | ไม่มี |',
                '| overhead/ความเร็ว | สูงกว่า/ช้ากว่า | ต่ำกว่า/เร็วกว่า |',
                '',
                'พอร์ตที่ควรจำ (well-known ports 0–1023):',
                '',
                '| พอร์ต | บริการ | L4 |',
                '|---|---|---|',
                '| 22 | SSH | TCP |',
                '| 53 | DNS | UDP (และ TCP) |',
                '| 80 | HTTP | TCP |',
                '| 443 | HTTPS | TCP |',
                '| 123 | NTP | UDP |',
                '| 67/68 | DHCP | UDP |',
              ].join('\n'),
            },
          ],
        },
        {
          type: 'quiz',
          title: 'แบบทดสอบ — TCP เทียบ UDP',
          order: 3,
          estMinutes: 5,
          passThreshold: 60,
          questions: [
            {
              prompt: 'ลำดับการจับมือ (3-way handshake) ของ TCP คือข้อใด',
              choices: ['ACK → SYN → SYN-ACK', 'SYN → SYN-ACK → ACK', 'SYN → ACK → FIN', 'SYN-ACK → SYN → ACK'],
              answer: [1],
              explanation: 'TCP เปิดการเชื่อมต่อด้วย SYN → SYN-ACK → ACK ก่อนเริ่มส่งข้อมูลจริง',
              points: 1,
            },
            {
              prompt: 'แอปแบบเรียลไทม์อย่าง VoIP มักใช้ protocol ใดที่ชั้น Transport และเพราะอะไร',
              choices: [
                'TCP เพราะต้องการความน่าเชื่อถือสูงสุด',
                'UDP เพราะ overhead ต่ำและหน่วงน้อย ยอมให้ตกหล่นได้บ้าง',
                'IP เพราะอยู่ชั้นเดียวกัน',
                'ICMP เพราะส่งเสียงได้',
              ],
              answer: [1],
              explanation: 'VoIP ใช้ UDP เพราะความเร็ว/หน่วงต่ำสำคัญกว่า — แพ็กเก็ตเสียงที่มาช้าก็ไร้ประโยชน์',
              points: 1,
            },
            {
              prompt: 'กลไก windowing ของ TCP มีไว้เพื่ออะไร',
              choices: [
                'เข้ารหัสข้อมูล',
                'ควบคุมปริมาณข้อมูล (flow control) ไม่ให้ผู้ส่งกระหน่ำจนผู้รับล้น',
                'เลือกเส้นทาง routing',
                'แปลงชื่อเป็น IP',
              ],
              answer: [1],
              explanation: 'window size บอกว่าผู้รับรับเพิ่มได้อีกเท่าไรก่อนต้อง ACK เป็นการทำ flow control',
              points: 1,
            },
            {
              prompt: 'พอร์ต 443 ที่ใช้กับ HTTPS ทำงานบน protocol ชั้น Transport ใด',
              choices: ['UDP', 'TCP', 'ICMP', 'ARP'],
              answer: [1],
              explanation: 'HTTPS (443) ใช้ TCP เพราะต้องการการส่งที่เชื่อถือได้และเรียงลำดับ',
              points: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'โมดูล 2 — Ethernet และ Switching',
      description: 'MAC address, frame และวิธีที่ switch ส่งต่อข้อมูลภายใน LAN',
      order: 1,
      objectives: [
        'อธิบายโครงสร้าง Ethernet frame และ MAC address',
        'อธิบายการเรียนรู้ MAC และการ forward ของ switch',
        'ทดลองสื่อสารข้าม switch ใน broadcast domain เดียวกัน',
      ],
      lessons: [
        {
          type: 'reading',
          title: 'MAC Address และ Switch Forwarding',
          order: 0,
          estMinutes: 11,
          sections: [
            {
              heading: 'MAC Address',
              body: [
                'MAC address เป็นที่อยู่ Layer 2 ขนาด 48 บิต เขียนเป็นเลขฐานสิบหก เช่น `00:1A:2B:3C:4D:5E` ฝังมากับการ์ดเครือข่ายตั้งแต่โรงงาน (แต่เปลี่ยนได้)',
                '',
                'ต่างจาก IP ตรงที่ MAC ใช้สื่อสาร**ภายใน LAN เดียวกัน**เท่านั้น ขณะที่ IP ใช้ระบุปลายทางข้ามเครือข่าย',
              ].join('\n'),
            },
            {
              heading: 'switch เรียนรู้และส่งต่ออย่างไร',
              body: [
                'switch สร้าง **MAC address table** โดยจดจำว่า MAC ต้นทางมาจากพอร์ตใด',
                '',
                '1. **Learn** — เห็น frame เข้ามา จดว่า MAC ต้นทางอยู่พอร์ตนี้',
                '2. **Forward** — ถ้ารู้ว่า MAC ปลายทางอยู่พอร์ตใด ส่งออกเฉพาะพอร์ตนั้น',
                '3. **Flood** — ถ้ายังไม่รู้ปลายทาง (หรือเป็น broadcast) ส่งออกทุกพอร์ตยกเว้นพอร์ตที่รับมา',
                '',
                'หลาย switch ที่ต่อกันด้วย uplink ยังเป็น broadcast domain เดียวกัน host จึงคุยข้าม switch ได้โดยไม่ต้อง route',
              ].join('\n'),
            },
          ],
        },
        {
          type: 'lab',
          title: 'แล็บ — Multi-Switch LAN',
          order: 1,
          estMinutes: 25,
          description: 'ต่อ switch สองตัวเข้าด้วยกัน วาง host บนแต่ละ switch ใน subnet เดียวกัน แล้วยืนยันว่าสื่อสารข้าม uplink ได้',
          scenario: {
            from: 'คุณส้ม ผู้จัดการสำนักงาน',
            priority: 'medium',
            body: 'ออฟฟิศขยายไปชั้น 2 แล้วค่ะ ช่างเพิ่งติด switch ตัวใหม่บนนั้นและลากสายลงมาต่อกับตัวเดิมชั้น 1 ให้แล้ว แต่เครื่องชั้น 2 ยังใช้ printer กับ file server ชั้น 1 ไม่ได้เลย ทีมขายจะเข้าออฟฟิศใหม่จันทร์นี้ ฝากเซ็ตให้ทุกเครื่องทั้งสองชั้นมองเห็นกันด้วยนะคะ',
          },
          objectives: [
            'PC1, PC2 ต่ออยู่กับ SW1 และ PC3, PC4 ต่ออยู่กับ SW2',
            'SW1 กับ SW2 เชื่อมกันด้วย uplink หนึ่งเส้น',
            'ทุกเครื่องอยู่ใน 172.16.0.0/24 และ ping หากันได้ทั้งที่อยู่คนละ switch',
            'เข้าใจว่า switch ส่งต่อ frame ภายใน broadcast domain เดียวกัน',
          ],
          hints: [
            'ตั้ง IP เช่น `ip 172.16.0.11 255.255.255.0` บนแต่ละ PC ให้ host part ไม่ซ้ำกัน',
            'การสื่อสารข้าม switch อาศัย uplink ระหว่าง SW1–SW2 ถ้าลิงก์นี้หลุด PC คนละฝั่งจะ ping ไม่ถึง',
            'ลอง `trace 172.16.0.44` จะเห็นว่าถึงปลายทางใน hop เดียว เพราะเป็น L2 เดียวกัน',
          ],
          topology: {
            nodes: [
              { name: 'PC1', nodeType: 'vpcs', x: -300, y: -80 },
              { name: 'PC2', nodeType: 'vpcs', x: -300, y: 80 },
              { name: 'PC3', nodeType: 'vpcs', x: 300, y: -80 },
              { name: 'PC4', nodeType: 'vpcs', x: 300, y: 80 },
              { name: 'SW1', nodeType: 'ethernet_switch', x: -120, y: 0 },
              { name: 'SW2', nodeType: 'ethernet_switch', x: 120, y: 0 },
            ],
            links: [
              { node1: 'PC1', port1: 0, node2: 'SW1', port2: 0 },
              { node1: 'PC2', port1: 0, node2: 'SW1', port2: 1 },
              { node1: 'PC3', port1: 0, node2: 'SW2', port2: 0 },
              { node1: 'PC4', port1: 0, node2: 'SW2', port2: 1 },
              { node1: 'SW1', port1: 7, node2: 'SW2', port2: 7 },
            ],
          },
          gradingChecks: [
            { description: 'PC1 มี IP 172.16.0.11/24', node: 'PC1', command: 'show ip', expect: '172\\.16\\.0\\.11/24', points: 1,
              failHint: 'PC1 ยังไม่ได้ IP ตามแผน — พิมพ์ `ip 172.16.0.11 255.255.255.0` ใน console ของ PC1 (สังเกตว่า mask /24 = 255.255.255.0)' },
            { description: 'PC4 มี IP 172.16.0.44/24', node: 'PC4', command: 'show ip', expect: '172\\.16\\.0\\.44/24', points: 1,
              failHint: 'PC4 ยังไม่ได้ IP ตามแผน — พิมพ์ `ip 172.16.0.44 255.255.255.0` ใน console ของ PC4' },
            { description: 'PC1 ping PC2 ได้ (SW1 เดียวกัน)', node: 'PC1', command: 'ping 172.16.0.22', expect: 'bytes from 172\\.16\\.0\\.22', points: 2,
              failHint: 'เครื่องบน switch เดียวกันยังคุยกันไม่ได้ — เช็ค `show ip` ของ PC2 ว่าตั้ง 172.16.0.22/24 แล้วหรือยัง ถ้าวง L2 เดียวกัน IP ถูก ก็ต้อง ping ถึง' },
            { description: 'PC1 ping PC3 ได้ (ข้าม SW1→SW2)', node: 'PC1', command: 'ping 172.16.0.33', expect: 'bytes from 172\\.16\\.0\\.33', points: 3,
              failHint: 'ข้าม switch ไม่ถึง — ถ้า ping ใน SW1 ได้แต่ข้ามไป SW2 ไม่ได้ ปัญหาอยู่ที่ IP ฝั่ง PC3 หรือ uplink ระหว่าง SW1–SW2 ลองดู topology ว่าลิงก์เส้นกลางยังอยู่ไหม' },
            { description: 'PC1 ping PC4 ได้ (ข้าม SW1→SW2)', node: 'PC1', command: 'ping 172.16.0.44', expect: 'bytes from 172\\.16\\.0\\.44', points: 3,
              failHint: 'ยังไปไม่ถึง PC4 — ทุกเครื่องต้องอยู่วง 172.16.0.x/24 เดียวกัน เทียบ `show ip` ของ PC1 กับ PC4 ว่า network part ตรงกันหรือไม่' },
          ],
        },
        {
          type: 'quiz',
          title: 'แบบทดสอบ — Ethernet & Switching',
          order: 2,
          estMinutes: 5,
          passThreshold: 60,
          questions: [
            {
              prompt: 'เมื่อ switch ยังไม่รู้ว่า MAC ปลายทางอยู่พอร์ตใด มันจะทำอย่างไร',
              choices: ['ทิ้ง frame', 'ส่งออกทุกพอร์ตยกเว้นพอร์ตต้นทาง (flood)', 'ส่งกลับพอร์ตเดิม', 'แปลงเป็น IP'],
              answer: [1],
              explanation: 'เมื่อไม่รู้ปลายทาง switch จะ flood ออกทุกพอร์ตยกเว้นพอร์ตที่รับมา',
              points: 1,
            },
            {
              prompt: 'MAC address มีขนาดกี่บิต',
              choices: ['32 บิต', '48 บิต', '64 บิต', '128 บิต'],
              answer: [1],
              explanation: 'MAC address มี 48 บิต เขียนเป็นเลขฐาน 16 จำนวน 12 หลัก',
              points: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'โมดูล 3 — Network Layer: IPv4 และ IPv6',
      description: 'การ routing เบื้องต้น และความแตกต่างระหว่าง IPv4 กับ IPv6',
      order: 2,
      objectives: [
        'อธิบายหน้าที่ของ router และ routing table',
        'เปรียบเทียบ IPv4 กับ IPv6',
        'อธิบายเหตุผลที่ต้องมี IPv6',
      ],
      lessons: [
        {
          type: 'reading',
          title: 'Routing เบื้องต้นและ IPv6',
          order: 0,
          estMinutes: 12,
          sections: [
            {
              heading: 'router ตัดสินใจอย่างไร',
              body: [
                'router เก็บ **routing table** ที่บอกว่า network ปลายทางใดควรส่งออกทาง interface ใด (หรือ next-hop ใด)',
                '',
                'เมื่อ packet เข้ามา router จะ:',
                '1. อ่าน IP ปลายทาง',
                '2. หา route ที่ตรงที่สุด (longest prefix match)',
                '3. ส่ง packet ออกตาม route นั้น หรือทิ้งถ้าไม่มี route',
                '',
                'route เกิดได้จาก: directly connected, static route (ตั้งเอง), หรือ dynamic routing protocol (OSPF, EIGRP)',
              ].join('\n'),
            },
            {
              heading: 'ทำไมต้อง IPv6',
              body: [
                'IPv4 มี 32 บิต = ~4.3 พันล้านที่อยู่ ซึ่ง**หมดแล้ว** IPv6 จึงถูกออกแบบด้วย 128 บิต ให้ที่อยู่มหาศาล',
                '',
                '| | IPv4 | IPv6 |',
                '|--|------|------|',
                '| ขนาด | 32 บิต | 128 บิต |',
                '| รูปแบบ | 192.168.1.1 | 2001:db8::1 |',
                '| broadcast | มี | ไม่มี (ใช้ multicast แทน) |',
                '',
                'IPv6 เขียนเป็นเลขฐาน 16 8 กลุ่ม คั่นด้วย `:` และย่อ 0 ติดกันด้วย `::` ได้หนึ่งครั้ง',
              ].join('\n'),
            },
          ],
        },
        {
          type: 'quiz',
          title: 'แบบทดสอบ — Network Layer',
          order: 1,
          estMinutes: 5,
          passThreshold: 60,
          questions: [
            {
              prompt: 'router ใช้หลักการใดในการเลือก route ที่ตรงที่สุด',
              choices: ['Shortest IP', 'Longest prefix match', 'Lowest MAC', 'Random'],
              answer: [1],
              explanation: 'router เลือก route ที่ prefix ยาว/เจาะจงที่สุดที่ตรงกับ IP ปลายทาง (longest prefix match)',
              points: 1,
            },
            {
              prompt: 'IPv6 มีขนาดที่อยู่กี่บิต',
              choices: ['32', '64', '128', '256'],
              answer: [2],
              explanation: 'IPv6 มี 128 บิต ทำให้มีจำนวนที่อยู่มหาศาล',
              points: 1,
            },
            {
              prompt: 'ข้อใดถูกต้องเกี่ยวกับ IPv6',
              choices: [
                'ใช้ broadcast เหมือน IPv4',
                'ไม่มี broadcast ใช้ multicast แทน',
                'มีขนาด 32 บิต',
                'เขียนเป็นเลขฐานสิบ',
              ],
              answer: [1],
              explanation: 'IPv6 ไม่มี broadcast แต่ใช้ multicast/anycast แทน',
              points: 1,
            },
          ],
        },
      ],
    },
    {
      title: 'โมดูล 4 — การวินิจฉัยและแก้ปัญหาเครือข่าย',
      description: 'ใช้เครื่องมือ ping/trace อย่างเป็นระบบ และซ่อม host ที่ตั้งค่าผิด',
      order: 3,
      objectives: [
        'ใช้ ping และ trace วินิจฉัยปัญหาอย่างเป็นขั้นตอน',
        'ระบุสาเหตุที่ host ping ไม่ถึงกัน',
        'แก้ไขการตั้งค่า IP/mask ที่ผิดได้',
      ],
      lessons: [
        {
          type: 'reading',
          title: 'วิธีคิดแบบ Troubleshooting',
          order: 0,
          estMinutes: 8,
          sections: [
            {
              heading: 'ไล่จากล่างขึ้นบน',
              body: [
                'แนวทางที่นิยมคือไล่ตามชั้น OSI **จากล่างขึ้นบน**:',
                '',
                '1. **L1** — สายต่อครบไหม ไฟ link ติดไหม',
                '2. **L2** — switch เห็น MAC ไหม',
                '3. **L3** — IP/mask/gateway ถูกไหม (`show ip`)',
                '4. **L4+** — service/port เปิดไหม',
                '',
                'เครื่องมือคู่ใจ: `ping` ตรวจ reachability, `trace` ดูเส้นทางแต่ละ hop',
              ].join('\n'),
            },
            {
              heading: 'อาการที่พบบ่อย',
              body: [
                '- ping ภายใน subnet ไม่ผ่าน → มักเป็น IP/mask ผิด หรือ host part ซ้ำ',
                '- ping ภายในได้ แต่ออกนอกไม่ได้ → มักเป็น gateway ผิด/ไม่ได้ตั้ง',
                '- ทุกอย่างถูกแต่ยังไม่ได้ → ตรวจสาย/พอร์ตที่ switch',
                '',
                '> เปลี่ยนทีละอย่าง แล้วทดสอบใหม่ จะหาเหตุได้ไวกว่าการเดา',
              ].join('\n'),
            },
          ],
        },
        {
          type: 'lab',
          title: 'แล็บ — Fix the Broken Host',
          order: 1,
          estMinutes: 25,
          description: 'PC ทั้งหมดต้อง ping หากันได้ใน 192.168.50.0/24 — ลงมือตั้งค่า host ทุกเครื่องให้ถูก subnet/mask แล้วพิสูจน์ด้วย ping',
          scenario: {
            from: 'คุณสมศรี ฝ่ายบัญชี',
            priority: 'high',
            body: 'เครื่องในห้องบัญชีใช้ระบบแชร์ไฟล์กันไม่ได้มาตั้งแต่เช้าค่ะ! บางเครื่องเห็นกัน บางเครื่องหายไปเฉย ๆ วันนี้ต้องปิดงบสิ้นเดือน ผู้สอบบัญชีนั่งรออยู่ ฝากดูด่วนเลยนะคะ — ได้ยินว่าเมื่อวานมีน้องฝึกงานมา "ช่วยจัด IP ใหม่" ให้ทั้งห้อง',
          },
          objectives: [
            'วิเคราะห์ว่า host ที่ ping ไม่ถึงเกิดจาก IP/mask ผิด subnet',
            'ตั้งค่า PC1 = 192.168.50.10/24, PC2 = 192.168.50.20/24, PC3 = 192.168.50.30/24',
            'ยืนยันว่าทุกเครื่อง ping หากันได้หลังแก้ไข',
          ],
          hints: [
            'mask /24 (255.255.255.0) ต้องเหมือนกันทุกเครื่อง และ network part (192.168.50) ต้องตรงกัน',
            'ถ้า ping ขึ้น "host not reachable" ให้ใช้ `show ip` เทียบ IP/MASK ของแต่ละเครื่อง',
            'host part (เลขชุดสุดท้าย) ต้องไม่ซ้ำกัน และต้องไม่ใช่ .0 หรือ .255',
          ],
          topology: {
            nodes: [
              { name: 'PC1', nodeType: 'vpcs', x: -200, y: -100 },
              { name: 'PC2', nodeType: 'vpcs', x: 200, y: -100 },
              { name: 'PC3', nodeType: 'vpcs', x: 0, y: 150 },
              { name: 'SW1', nodeType: 'ethernet_switch', x: 0, y: 0 },
            ],
            links: [
              { node1: 'PC1', port1: 0, node2: 'SW1', port2: 0 },
              { node1: 'PC2', port1: 0, node2: 'SW1', port2: 1 },
              { node1: 'PC3', port1: 0, node2: 'SW1', port2: 2 },
            ],
          },
          gradingChecks: [
            { description: 'PC1 อยู่ใน 192.168.50.0/24', node: 'PC1', command: 'show ip', expect: '192\\.168\\.50\\.10/24', points: 2,
              failHint: 'PC1 ต้องเป็น 192.168.50.10/24 — ใช้ `show ip` ดูค่าปัจจุบันก่อน แล้วแก้ด้วย `ip 192.168.50.10 255.255.255.0`' },
            { description: 'PC2 อยู่ใน 192.168.50.0/24', node: 'PC2', command: 'show ip', expect: '192\\.168\\.50\\.20/24', points: 2,
              failHint: 'PC2 ต้องเป็น 192.168.50.20/24 — สังเกตทั้ง IP และ MASK ใน `show ip` ผิดอย่างใดอย่างหนึ่งก็ทำให้คนละ subnet ได้' },
            { description: 'PC3 อยู่ใน 192.168.50.0/24', node: 'PC3', command: 'show ip', expect: '192\\.168\\.50\\.30/24', points: 2,
              failHint: 'PC3 ต้องเป็น 192.168.50.30/24 — ระวัง mask ที่ไม่ใช่ /24 เช่น 255.255.0.0 จะทำให้ดูเหมือนถูกแต่ผิด subnet' },
            { description: 'PC1 ping PC2 ได้', node: 'PC1', command: 'ping 192.168.50.20', expect: 'bytes from 192\\.168\\.50\\.20', points: 2,
              failHint: 'PC1→PC2 ยังไม่ถึง — เทียบ `show ip` ของทั้งคู่: network part ต้องเป็น 192.168.50 และ mask /24 เหมือนกันทั้งสองเครื่อง' },
            { description: 'PC2 ping PC3 ได้', node: 'PC2', command: 'ping 192.168.50.30', expect: 'bytes from 192\\.168\\.50\\.30', points: 2,
              failHint: 'PC2→PC3 ยังไม่ถึง — ถ้าแก้ IP แล้วแต่ยังไม่ผ่าน เช็คว่า host part ไม่ซ้ำกับเครื่องอื่น และไม่ใช่ .0/.255' },
          ],
        },
        {
          type: 'quiz',
          title: 'แบบทดสอบท้ายโมดูล 4',
          order: 2,
          estMinutes: 4,
          passThreshold: 60,
          questions: [
            {
              prompt: 'host A ping host B ในวงเดียวกันไม่ผ่าน สาเหตุที่น่าจะเป็นไปได้มากที่สุดคือข้อใด',
              choices: ['gateway ผิด', 'IP/mask ผิด subnet หรือ host part ซ้ำ', 'DNS ล่ม', 'เว็บเซิร์ฟเวอร์ดับ'],
              answer: [1],
              explanation: 'การ ping ภายใน subnet ไม่เกี่ยวกับ gateway/DNS มักเกิดจาก IP/mask ผิดหรือ host ซ้ำ',
              points: 1,
            },
            {
              prompt: 'เครื่องมือใดใช้ดูเส้นทาง (แต่ละ hop) ไปยังปลายทาง',
              choices: ['ping', 'trace / traceroute', 'show ip', 'arp'],
              answer: [1],
              explanation: 'trace/traceroute แสดง hop ตลอดเส้นทาง ส่วน ping บอกแค่ถึง/ไม่ถึง',
              points: 1,
            },
          ],
        },
      ],
    },
  ],
};
